<?php

/**
 * Auth and registration options.
 */

return [
    'districts' => [
        'Colombo District',
        'Gampaha District',
        'Kalutara District',
        'Kandy District',
        'Kegalle District',
        'Ratnapura District',
        'Polonnaruwa District',
        'Badulla District',
        'Galle District',
        'Matara District',
    ],

    'gn_divisions' => [
        'Colombo District' => [
            'Colombo',
            'Kolonnawa',
            'Nagalagam Street',
            'Kaduwela',
            'Homagama',
            'Hanwella (Seethawaka)',
            'Hanwella',
            'Padukka',
            'Maharagama',
            'Sri Jayawardenepura Kotte',
            'Thimbirigasyaya',
            'Dehiwala',
            'Ratmalana',
            'Moratuwa',
            'Kesbewa',
        ],
        'Gampaha District' => [
            'Negombo',
            'Katana',
            'Divulapitiya',
            'Mirigama',
            'Minuwangoda',
            'Wattala',
            'Ja-Ela',
            'Gampaha',
            'Attanagalla',
            'Dompe',
            'Mahara',
            'Kelaniya',
            'Biyagama',
        ],
        'Kalutara District' => [
            'Avissawella',
            'Glencourse',
            'Panadura',
            'Bandaragama',
            'Horana',
            'Ingiriya',
            'Bulathsinhala',
            'Madurawala',
            'Millaniya',
            'Kalutara',
            'Beruwala',
            'Dodangoda',
            'Matugama',
            'Agalawatta',
            'Palindanuwara',
            'Walallavita',
        ],
        'Kandy District' => [
            'Thumpane',
            'Pujapitiya',
            'Akurana',
            'Pathadumbara',
            'Panvila',
            'Ududumbara',
            'Minipe',
            'Medadumbara',
            'Kundasale',
            'Kandy Four Gravets',
            'Gangawata Korale',
            'Yatinuwara',
            'Udunuwara',
            'Doluwa',
            'Pathahewaheta',
            'Delthota',
            'Udapalatha',
            'Ganga Ihala Korale',
            'Pasbage Korale',
            'Hatharaliyadda',
            'Nawalapitiya',
            'Peradeniya',
            'Weraganthota',
        ],
        'Kegalle District' => [
            'Deraniyagala',
            'Holombuwa',
            'Kithulgala',
            'Mawanella',
            'Ruwanwella',
            'Yatiyanthota',
            'Warakapola',
        ],
        'Ratnapura District' => [
            'Rathnapura',
            'Ellagawa',
            'Kalawellawa',
            'Magura',
            'Putupaula',
            'Kuruwita',
            'Pelmadulla',
            'Balangoda',
            'Eheliyagoda',
            'Godakawela',
        ],
        'Polonnaruwa District' => [
            'Manampitiya',
            'Dimbulagala',
            'Polonnaruwa',
            'Hingurakgoda',
            'Lankapura',
            'Welikanda',
        ],
        'Badulla District' => [
            'Thaldena',
            'Welimada',
            'Badulla',
            'Passara',
            'Bandarawela',
            'Hali-Ela',
        ],
        'Galle District' => [
            'Bentota',
            'Balapitiya',
            'Karandeniya',
            'Elpitiya',
            'Talape',
            'Galle Four Gravets',
            'Bope-Poddala',
            'Akmeemana',
            'Yakkalamulla',
            'Imaduwa',
            'Habaraduwa',
            'Baddegama',
            'Nagoda',
            'Neluwa',
            'Thawalama',
            'Welivitiya-Divithura',
            'Ambalangoda',
            'Hikkaduwa',
            'Gonapinuwala',
        ],
        'Matara District' => [
            'Pitabeddara',
            'Kotapola',
            'Pasgoda',
            'Mulatiyana',
            'Athuraliya',
            'Akuressa',
            'Welipitiya',
            'Malimbada',
            'Kamburupitiya',
            'Hakmana',
            'Kirinda-Puhulwella',
            'Thihagoda',
            'Weligama',
            'Matara Four Gravets',
            'Devinuwara',
            'Dickwella',
        ],
    ],

    'volunteer_preferences' => [
        'Search & Rescue',
        'Medical Aid',
        'Logistics Support',
        'Technical Support',
        'Shelter Management',
        'Food Preparation & Distribution',
        'Childcare Support',
        'Elderly Assistance',
    ],

    'volunteer_skills' => [
        'First Aid Certified',
        'Medical Professional',
        'Firefighting',
        'Swimming / Lifesaving',
        'Rescue & Handling',
        'Disaster Management Training',
    ],

    'genders' => ['male', 'female', 'other'],
];
