<?php

/**
 * River discharge flood thresholds per station.
 * Derived from 5-year historical mean (2020-2024) via Open-Meteo GloFAS.
 * Thresholds: alert = 2x mean, minor = 5x mean, major = 10x mean.
 *
 * Generated by: php tools/discharge_baselines/compute.php
 * Generated at (UTC): 2026-04-13T08:14:58+00:00
 *
 * DO NOT EDIT MANUALLY.
 */

function forecast_discharge_thresholds(): array
{
    return [
        'ampara' => [
            // Ampara
            'mean' => 34.07,
            'alert' => 68.14,
            'minor' => 170.36,
            'major' => 340.72,
        ],
        'badalgama' => [
            // Badalgama
            'mean' => 54.63,
            'alert' => 109.27,
            'minor' => 273.17,
            'major' => 546.34,
        ],
        'baddegama' => [
            // Baddegama
            'mean' => 35.80,
            'alert' => 71.61,
            'minor' => 179.01,
            'major' => 358.03,
        ],
        'deraniyagala' => [
            // Deraniyagala
            'mean' => 15.28,
            'alert' => 30.56,
            'minor' => 76.39,
            'major' => 152.78,
        ],
        'dunamale' => [
            // Dunamale
            'mean' => 7.96,
            'alert' => 15.91,
            'minor' => 39.78,
            'major' => 79.56,
        ],
        'ellagawa' => [
            // Ellagawa
            'mean' => 106.34,
            'alert' => 212.69,
            'minor' => 531.72,
            'major' => 1063.44,
        ],
        'galgamuwa' => [
            // Galgamuwa
            'mean' => 0.38,
            'alert' => 0.76,
            'minor' => 1.90,
            'major' => 3.80,
        ],
        'giriulla' => [
            // Giriulla
            'mean' => 8.26,
            'alert' => 16.52,
            'minor' => 41.29,
            'major' => 82.59,
        ],
        'glencourse' => [
            // Glencourse
            'mean' => 132.15,
            'alert' => 264.30,
            'minor' => 660.74,
            'major' => 1321.48,
        ],
        'hanwella' => [
            // Hanwella
            'mean' => 7.76,
            'alert' => 15.52,
            'minor' => 38.79,
            'major' => 77.58,
        ],
        'holombuwa' => [
            // Holombuwa
            'mean' => 8.20,
            'alert' => 16.39,
            'minor' => 40.99,
            'major' => 81.97,
        ],
        'horowpothana' => [
            // Horowpothana
            'mean' => 2.74,
            'alert' => 5.49,
            'minor' => 13.72,
            'major' => 27.44,
        ],
        'kalawellawa_millakanda' => [
            // Kalawellawa (Millakanda)
            'mean' => 56.10,
            'alert' => 112.20,
            'minor' => 280.50,
            'major' => 561.00,
        ],
        'katharagama' => [
            // Katharagama
            'mean' => 15.10,
            'alert' => 30.21,
            'minor' => 75.51,
            'major' => 151.03,
        ],
        'kithulgala' => [
            // Kithulgala
            'mean' => 20.97,
            'alert' => 41.95,
            'minor' => 104.87,
            'major' => 209.75,
        ],
        'kuda_oya' => [
            // Kuda Oya
            'mean' => 0.24,
            'alert' => 0.49,
            'minor' => 1.22,
            'major' => 2.45,
        ],
        'magura' => [
            // Magura
            'mean' => 4.03,
            'alert' => 8.07,
            'minor' => 20.17,
            'major' => 40.33,
        ],
        'manampitiya' => [
            // Manampitiya
            'mean' => 177.47,
            'alert' => 354.93,
            'minor' => 887.33,
            'major' => 1774.65,
        ],
        'moragaswewa' => [
            // Moragaswewa
            'mean' => 0.62,
            'alert' => 1.24,
            'minor' => 3.11,
            'major' => 6.22,
        ],
        'moraketiya' => [
            // Moraketiya
            'mean' => 0.36,
            'alert' => 0.72,
            'minor' => 1.80,
            'major' => 3.59,
        ],
        'nagalagam_street' => [
            // Nagalagam Street
            'mean' => 2.23,
            'alert' => 4.46,
            'minor' => 11.15,
            'major' => 22.31,
        ],
        'nakkala' => [
            // Nakkala
            'mean' => 4.32,
            'alert' => 8.64,
            'minor' => 21.60,
            'major' => 43.20,
        ],
        'nawalapitiya' => [
            // Nawalapitiya
            'mean' => 2.22,
            'alert' => 4.43,
            'minor' => 11.08,
            'major' => 22.16,
        ],
        'norwood' => [
            // Norwood
            'mean' => 6.36,
            'alert' => 12.71,
            'minor' => 31.78,
            'major' => 63.56,
        ],
        'padiyathalawa' => [
            // Padiyathalawa
            'mean' => 3.00,
            'alert' => 6.01,
            'minor' => 15.02,
            'major' => 30.03,
        ],
        'panadugama' => [
            // Panadugama
            'mean' => 1.07,
            'alert' => 2.15,
            'minor' => 5.37,
            'major' => 10.73,
        ],
        'peradeniya' => [
            // Peradeniya
            'mean' => 67.82,
            'alert' => 135.64,
            'minor' => 339.11,
            'major' => 678.22,
        ],
        'pitabeddara' => [
            // Pitabeddara
            'mean' => 1.26,
            'alert' => 2.51,
            'minor' => 6.28,
            'major' => 12.56,
        ],
        'putupaula' => [
            // Putupaula
            'mean' => 66.94,
            'alert' => 133.89,
            'minor' => 334.71,
            'major' => 669.43,
        ],
        'rathnapura' => [
            // Rathnapura
            'mean' => 45.00,
            'alert' => 90.01,
            'minor' => 225.02,
            'major' => 450.03,
        ],
        'siyambalanduwa' => [
            // Siyambalanduwa
            'mean' => 0.52,
            'alert' => 1.05,
            'minor' => 2.62,
            'major' => 5.24,
        ],
        'thaldena' => [
            // Thaldena
            'mean' => 9.08,
            'alert' => 18.16,
            'minor' => 45.40,
            'major' => 90.81,
        ],
        'thalgahagoda' => [
            // Thalgahagoda
            'mean' => 2.92,
            'alert' => 5.85,
            'minor' => 14.62,
            'major' => 29.24,
        ],
        'thanamalwila' => [
            // Thanamalwila
            'mean' => 0.21,
            'alert' => 0.43,
            'minor' => 1.07,
            'major' => 2.15,
        ],
        'thanthirimale' => [
            // Thanthirimale
            'mean' => 6.73,
            'alert' => 13.47,
            'minor' => 33.66,
            'major' => 67.33,
        ],
        'thawalama' => [
            // Thawalama
            'mean' => 1.78,
            'alert' => 3.55,
            'minor' => 8.88,
            'major' => 17.76,
        ],
        'urawa' => [
            // Urawa
            'mean' => 0.89,
            'alert' => 1.78,
            'minor' => 4.44,
            'major' => 8.89,
        ],
        'wellawaya' => [
            // Wellawaya
            'mean' => 0.52,
            'alert' => 1.04,
            'minor' => 2.61,
            'major' => 5.21,
        ],
        'weraganthota' => [
            // Weraganthota                            
            'mean' => 0.53,
            'alert' => 1.06,
            'minor' => 2.65,
            'major' => 5.30,
        ],
        'yaka_wewa' => [
            // Yaka Wewa
            'mean' => 1.11,
            'alert' => 2.22,
            'minor' => 5.55,
            'major' => 11.10,
        ],
    ];
}
