<?php

/**
 * River discharge flood thresholds for monitored basin locations.
 * Derived from 5-year historical mean (2020-2024) via Open-Meteo GloFAS.
 * Thresholds: alert = 2x mean, minor = 3x mean, major = 5x mean.
 *
 * Generated by: php tools/discharge_baselines/compute.php
 * Generated at (UTC): 2026-04-13T10:49:43+00:00
 *
 * DO NOT EDIT MANUALLY.
 */

function forecast_discharge_thresholds(): array
{
    return [
        'deraniyagala' => [
            // Deraniyagala
            'mean' => 15.28,
            'alert' => 30.56,
            'minor' => 45.83,
            'major' => 76.39,
        ],
        'ellagawa' => [
            // Ellagawa
            'mean' => 106.34,
            'alert' => 212.69,
            'minor' => 319.03,
            'major' => 531.72,
        ],
        'glencourse' => [
            // Glencourse
            'mean' => 132.15,
            'alert' => 264.30,
            'minor' => 396.44,
            'major' => 660.74,
        ],
        'hanwella' => [
            // Hanwella
            'mean' => 7.76,
            'alert' => 15.52,
            'minor' => 23.27,
            'major' => 38.79,
        ],
        'holombuwa' => [
            // Holombuwa
            'mean' => 8.20,
            'alert' => 16.39,
            'minor' => 24.59,
            'major' => 40.99,
        ],
        'kalawellawa' => [
            // Kalawellawa
            'mean' => 56.10,
            'alert' => 112.20,
            'minor' => 168.30,
            'major' => 280.50,
        ],
        'kithulgala' => [
            // Kithulgala
            'mean' => 20.97,
            'alert' => 41.95,
            'minor' => 62.92,
            'major' => 104.87,
        ],
        'magura' => [
            // Magura
            'mean' => 4.03,
            'alert' => 8.07,
            'minor' => 12.10,
            'major' => 20.17,
        ],
        'manampitiya' => [
            // Manampitiya
            'mean' => 177.47,
            'alert' => 354.93,
            'minor' => 532.40,
            'major' => 887.33,
        ],
        'nagalagam_street' => [
            // Nagalagam Street
            'mean' => 2.23,
            'alert' => 4.46,
            'minor' => 6.69,
            'major' => 11.15,
        ],
        'nawalapitiya' => [
            // Nawalapitiya
            'mean' => 2.22,
            'alert' => 4.43,
            'minor' => 6.65,
            'major' => 11.08,
        ],
        'peradeniya' => [
            // Peradeniya
            'mean' => 67.82,
            'alert' => 135.64,
            'minor' => 203.47,
            'major' => 339.11,
        ],
        'putupaula' => [
            // Putupaula
            'mean' => 66.94,
            'alert' => 133.89,
            'minor' => 200.83,
            'major' => 334.71,
        ],
        'rathnapura' => [
            // Rathnapura
            'mean' => 45.00,
            'alert' => 90.01,
            'minor' => 135.01,
            'major' => 225.02,
        ],
        'thaldena' => [
            // Thaldena
            'mean' => 9.08,
            'alert' => 18.16,
            'minor' => 27.24,
            'major' => 45.40,
        ],
        'weraganthota' => [
            // Weraganthota
            'mean' => 0.53,
            'alert' => 1.06,
            'minor' => 1.59,
            'major' => 2.65,
        ],
    ];
}
